---
env:
  node: true
  es6: true

extends:
  - airbnb-base

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2018
  sourceType: module

plugins:
  - "@typescript-eslint"
  - import

rules:
  class-methods-use-this: 0,
  no-console: 0,
  import/prefer-default-export: 0,

settings:
  import/parsers:
    - "@typescript-eslint/parser": [".ts", ".tsx"]
  import/resolver:
    - typescript: {}
    - typescript:
        - directory: ./path/to/folder
